name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x' 

    - name: Install versionize
      run: dotnet tool install --global Versionize

    - name: Setup git
      run: |
        git config --global user.email opencommissioning@spiratec.com
        git config --global user.name "oc-bot"
      
    - name: Versioning
      run: versionize --exit-insignificant-commits

    - name: Get current version and changelog
      run: |
        cd ./OC.Assistant
        $version = versionize inspect
        echo "VERSION=v$version" >> $env:GITHUB_ENV
        $changelog = versionize changelog
        New-Item -ItemType Directory -Force -Path ../publish | Out-Null
        Set-Content -Path ../publish/latest_changelog.md -Value $changelog
      shell: pwsh
      
    #- name: Clone and add twincat reference
    #  run: |
    #    git clone https://github.com/OpenCommissioning/OC_Assistant_Twincat.git publish/twincat
    #    dotnet add reference publish/twincat/OC.Twincat/OC.Twincat.csproj --project OC.Assistant

    - name: Dotnet publish assistant
      run: |
        dotnet publish `
          OC.Assistant `
          --configuration release `
          --runtime win-x64 `
          --no-self-contained `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:IncludeAllContentForSelfExtract=true
        
    #- name: Remove twincat reference
    #  run: dotnet reference remove publish/twincat/OC.Twincat/OC.Twincat.csproj --project OC.Assistant

    - name: Install azuresigntool
      run: dotnet tool install --global azuresigntool

    - name: Sign executable
      run: |
        azuresigntool sign `
          -kvu ${{secrets.AZURE_KEY_VAULT}} `
          -kvc ${{secrets.AZURE_CERT_NAME}} `
          -kvt ${{secrets.AZURE_TENANT_ID}} `
          -kvi ${{secrets.AZURE_CLIENT_ID}} `
          -kvs ${{secrets.AZURE_CLIENT_SECRET}} `
          -tr http://timestamp.globalsign.com/tsa/advanced `
          -td sha256 `
          ./OC.Assistant/bin/release/net10.0/win-x64/publish/OC.Assistant.exe

    - name: Zip signed executable
      run: |
        Compress-Archive `
          -Path ./OC.Assistant/bin/release/net10.0/win-x64/publish/OC.Assistant.exe `
          -DestinationPath ./publish/OC.Assistant_${{env.VERSION}}.zip
      shell: pwsh
      
    - name: Build sdk and push to nuget
      run: |
        dotnet build OC.Assistant.Sdk --configuration release
        dotnet nuget push "OC.Assistant.Sdk/bin/release/*.nupkg" `
          --api-key ${{secrets.NUGET_API_KEY}} `
          --source https://api.nuget.org/v3/index.json
      
    - name: Build ui and push to nuget
      run: |
        dotnet build OC.Assistant.Ui --configuration release
        dotnet nuget push "OC.Assistant.Ui/bin/release/*.nupkg" `
          --api-key ${{secrets.NUGET_API_KEY}} `
          --source https://api.nuget.org/v3/index.json
      
    - name: Push to github
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true

    - name: Create github release and upload artifacts
      run: |
        gh release create ${{env.VERSION}} -t "Release ${{env.VERSION}}" -F ./publish/latest_changelog.md
        gh release upload ${{env.VERSION}} ./publish/OC.Assistant_${{env.VERSION}}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
